### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by scarroll32** [anycable/capistrano-anycable#1]
Is seems to be a bit light on code. Is it ready?

Thanks :-)

**Comment by sponomarev** [comment]
@seanfcarroll We'll push the code this week. 😉

**Comment by scarroll32** [comment]
Just a friendly bump ...

**Comment by dmitry** [comment]
Also interested in official solution.

**Comment by scarroll32** [comment]
Friendly ping 🏓

**Comment by scarroll32** [comment]
Ping 🏓

**Comment by sponomarev** [comment]
@seanfcarroll Pong  🏓 #2

**Comment by sponomarev** [comment]
`0.1.0 ` has been released. Sorry, guys, for the delay. 🙏
