### ISSUE TITLE
Does this work? 

### ISSUE THREAD

**Issue by milushov** [anycable/capistrano-anycable#4]
As I see there is no information about RPC server and `anycable_command` command is outdated 🙈

**Comment by palkan** [comment]
`anycabled` is an RPC server daemon:

```ruby
# Command to start AnyCable
set :anycable_command, -> { [:bundle, :exec, :anycabled] }
```

It's used instead of a regular `anycable` command to make it possible to restart it on deployment.

**Comment by sponomarev** [comment]
I guess the confusion is that there's no mention that this Capistrano recipes deploy RPC but not the WS server. I'll mention in in the README.
